In [1]:
from statistics import median

import pandas as pd
import numpy as np
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
df.sample(11)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
263,0,1,male,40.0,0,0,0.0000,S,First,man,True,B,Southampton,no,True
461,0,3,male,34.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
170,0,1,male,61.0,0,0,33.5000,S,First,man,True,B,Southampton,no,True
220,1,3,male,16.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,yes,True
521,0,3,male,22.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
215,1,1,female,31.0,1,0,113.2750,C,First,woman,False,D,Cherbourg,yes,False
744,1,3,male,31.0,0,0,7.9250,S,Third,man,True,NaN,Southampton,yes,True
174,0,1,male,56.0,0,0,30.6958,C,First,man,True,A,Cherbourg,no,True
135,0,2,male,23.0,0,0,15.0458,C,Second,man,True,NaN,Cherbourg,no,True
491,0,3,male,21.0,0,0,7.2500,S,Third,man,True,NaN,Southampton,no,True
690,1,1,male,31.0,1,0,57.0000,S,First,man,True,B,Southampton,yes,False

### Bir xil malumotli ustunlar:
1. survived & alive, biz alive tushurib qoldiramiz,sabab u kategorikal
2. pclass va class : class ni tushirib qoldiramiz, sababi u kategorikal
3. sex,who,adult_male: 2tasini tushirib qoldiramiz

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [6]:
df = df.drop(columns=['alive', 'class', 'sex', 'adult_male'])
df.head()

,survived,pclass,age,sibsp,parch,fare,embarked,who,deck,embark_town,alone
0,0,3,22.0,1,0,7.2500,S,man,NaN,Southampton,False
1,1,1,38.0,1,0,71.2833,C,woman,C,Cherbourg,False
2,1,3,26.0,0,0,7.9250,S,woman,NaN,Southampton,True
3,1,1,35.0,1,0,53.1000,S,woman,C,Southampton,False
4,0,3,35.0,0,0,8.0500,S,man,NaN,Southampton,True

In [7]:
df.isna().sum()

survived         0
pclass           0
age            177
sibsp            0
parch            0
fare             0
embarked         2
who              0
deck           688
embark_town      2
alone            0
dtype: int64

In [8]:
df.isna().sum()/len(df)*100

survived        0.000000
pclass          0.000000
age            19.865320
sibsp           0.000000
parch           0.000000
fare            0.000000
embarked        0.224467
who             0.000000
deck           77.216611
embark_town     0.224467
alone           0.000000
dtype: float64

In [9]:
#Возраст запольняем с медианой
median = df['age'].median()
df['age'] = df['age'].fillna(median)

#Город заполняем с модой потому что категорикал
moda = df['embark_town'].mode()
df['embark_town']=df['embark_town'].fillna(moda)

In [10]:
df.groupby(['embark_town','embarked']).count()

,,survived,pclass,age,sibsp,parch,fare,who,deck,alone
embark_town,embarked,,,,,,,,,
Cherbourg,C,168,168,168,168,168,168,168,69,168
Queenstown,Q,77,77,77,77,77,77,77,4,77
Southampton,S,644,644,644,644,644,644,644,128,644

In [11]:
# Выбрасываем Embarked так как оно содержить меньше информацый чем Embarked town
df = df.drop(columns=['embarked'])

In [12]:
df.head()

,survived,pclass,age,sibsp,parch,fare,who,deck,embark_town,alone
0,0,3,22.0,1,0,7.2500,man,NaN,Southampton,False
1,1,1,38.0,1,0,71.2833,woman,C,Cherbourg,False
2,1,3,26.0,0,0,7.9250,woman,NaN,Southampton,True
3,1,1,35.0,1,0,53.1000,woman,C,Southampton,False
4,0,3,35.0,0,0,8.0500,man,NaN,Southampton,True

In [13]:
df = df.drop(columns=['deck'])

In [14]:
df.head()

   survived  pclass   age  sibsp  parch     fare    who  embark_town  alone
0         0       3  22.0      1      0   7.2500    man  Southampton  False
1         1       1  38.0      1      0  71.2833  woman    Cherbourg  False
2         1       3  26.0      0      0   7.9250  woman  Southampton   True
3         1       1  35.0      1      0  53.1000  woman  Southampton  False
4         0       3  35.0      0      0   8.0500    man  Southampton   True

In [18]:
moda = df['embark_town'].mode()
df['embark_town'] = df['embark_town'].fillna(moda[0])
df.isna().sum()

survived       0
pclass         0
age            0
sibsp          0
parch          0
fare           0
who            0
embark_town    0
alone          0
dtype: int64

In [99]:
df['who'] = df['who'].replace({'man':1, 'woman':0})
df['alone'] = df['alone'].replace({True:1, False:0})

In [100]:
df.head()

   survived  pclass   age  sibsp  parch     fare who  embark_town  alone
0         0       3  22.0      1      0   7.2500   1  Southampton      0
1         1       1  38.0      1      0  71.2833   0    Cherbourg      0
2         1       3  26.0      0      0   7.9250   0  Southampton      1
3         1       1  35.0      1      0  53.1000   0  Southampton      0
4         0       3  35.0      0      0   8.0500   1  Southampton      1

### Embark_town ustunini on-hot encoding orqali numerical ga otkazamiz, buning uchun pd.get_dummies()

In [108]:
new_collums = ['Cherbourg','Queenstown','Southampton']
df[new_collums] = pd.get_dummies(df['embark_town'],dtype=int)
df = df.drop(columns=['embark_town'])
df.head()

,survived,pclass,age,sibsp,parch,fare,who,alone,Cherbourg,Queenstown,Southampton
0,0,3,22.0,1,0,7.2500,1,0,0,0,1
1,1,1,38.0,1,0,71.2833,0,0,1,0,0
2,1,3,26.0,0,0,7.9250,0,1,0,0,1
3,1,1,35.0,1,0,53.1000,0,0,0,0,1
4,0,3,35.0,0,0,8.0500,1,1,0,0,1