# Apriori

## Importing the libraries

In [1]:
# !pip install apyori

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from apyori import apriori

## Data Preprocessing

In [3]:
dataset = pd.read_csv('../../data/Market_Basket_Optimisation.csv', header=None)

In [4]:
dataset

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,butter,light mayo,fresh bread,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7497,burgers,frozen vegetables,eggs,french fries,magazines,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7498,chicken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7499,escalope,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7500,eggs,frozen smoothie,yogurt cake,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
transactions = []

for i in range(0, 7501):
    transactions.append([str(dataset.values[i, j]) for j in range(0, 20) if str(dataset.values[i, j]) != 'nan'])

## Training the Apriori model on the dataset

In [6]:
rules = apriori(transactions=transactions, min_support=0.01, min_confidence=0.3, min_lift=1.01)

## Visualising the results

### Displaying the first results coming directly from the output of the apriori function

In [7]:
results = list(rules)

In [8]:
results

[RelationRecord(items=frozenset({'mineral water', 'avocado'}), support=0.011598453539528063, ordered_statistics=[OrderedStatistic(items_base=frozenset({'avocado'}), items_add=frozenset({'mineral water'}), confidence=0.348, lift=1.4599261744966443)]),
 RelationRecord(items=frozenset({'burgers', 'eggs'}), support=0.02879616051193174, ordered_statistics=[OrderedStatistic(items_base=frozenset({'burgers'}), items_add=frozenset({'eggs'}), confidence=0.33027522935779813, lift=1.8378297443715457)]),
 RelationRecord(items=frozenset({'mineral water', 'cake'}), support=0.027463004932675644, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cake'}), items_add=frozenset({'mineral water'}), confidence=0.33881578947368424, lift=1.4213966649005065)]),
 RelationRecord(items=frozenset({'cereals', 'mineral water'}), support=0.010265297960271964, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cereals'}), items_add=frozenset({'mineral water'}), confidence=0.3989637305699482, lift=1.6737287153272828)]),
 RelationRecord(items=frozenset({'mineral water', 'chicken'}), support=0.022796960405279298, ordered_statistics=[OrderedStatistic(items_base=frozenset({'chicken'}), items_add=frozenset({'mineral water'}), confidence=0.38000000000000006, lift=1.5941722595078303)]),
 RelationRecord(items=frozenset({'mineral water', 'chocolate'}), support=0.05265964538061592, ordered_statistics=[OrderedStatistic(items_base=frozenset({'chocolate'}), items_add=frozenset({'mineral water'}), confidence=0.3213995117982099, lift=1.3483320682317521)]),
 RelationRecord(items=frozenset({'mineral water', 'cooking oil'}), support=0.020130649246767097, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cooking oil'}), items_add=frozenset({'mineral water'}), confidence=0.3942558746736292, lift=1.6539783646123563)]),
 RelationRecord(items=frozenset({'cooking oil', 'spaghetti'}), support=0.01586455139314758, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cooking oil'}), items_add=frozenset({'spaghetti'}), confidence=0.31070496083550914, lift=1.7845313255950643)]),
 RelationRecord(items=frozenset({'eggs', 'turkey'}), support=0.01946407145713905, ordered_statistics=[OrderedStatistic(items_base=frozenset({'turkey'}), items_add=frozenset({'eggs'}), confidence=0.31130063965884863, lift=1.7322448798820649)]),
 RelationRecord(items=frozenset({'mineral water', 'fresh bread'}), support=0.013331555792560993, ordered_statistics=[OrderedStatistic(items_base=frozenset({'fresh bread'}), items_add=frozenset({'mineral water'}), confidence=0.30959752321981426, lift=1.2988204819193663)]),
 RelationRecord(items=frozenset({'mineral water', 'frozen smoothie'}), support=0.020263964804692707, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen smoothie'}), items_add=frozenset({'mineral water'}), confidence=0.32, lift=1.342460850111857)]),
 RelationRecord(items=frozenset({'mineral water', 'frozen vegetables'}), support=0.03572856952406346, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen vegetables'}), items_add=frozenset({'mineral water'}), confidence=0.37482517482517486, lift=1.57246288387228)]),
 RelationRecord(items=frozenset({'mineral water', 'grated cheese'}), support=0.0174643380882549, ordered_statistics=[OrderedStatistic(items_base=frozenset({'grated cheese'}), items_add=frozenset({'mineral water'}), confidence=0.3333333333333333, lift=1.3983967188665174)]),
 RelationRecord(items=frozenset({'spaghetti', 'grated cheese'}), support=0.01653112918277563, ordered_statistics=[OrderedStatistic(items_base=frozenset({'grated cheese'}), items_add=frozenset({'spaghetti'}), confidence=0.3155216284987277, lift=1.8121958157495839)]),
 RelationRecord(items=frozenset({'herb & pepper', 'ground beef'}), support=0.015997866951073192, ordered_statistics=[OrderedStatistic(items_base=frozenset({'herb & pepper'}), items_add=frozenset({'ground beef'}), confidence=0.3234501347708895, lift=3.2919938411349285)]),
 RelationRecord(items=frozenset({'mineral water', 'ground beef'}), support=0.040927876283162246, ordered_statistics=[OrderedStatistic(items_base=frozenset({'ground beef'}), items_add=frozenset({'mineral water'}), confidence=0.41655359565807326, lift=1.7475215442008991)]),
 RelationRecord(items=frozenset({'spaghetti', 'ground beef'}), support=0.03919477403012932, ordered_statistics=[OrderedStatistic(items_base=frozenset({'ground beef'}), items_add=frozenset({'spaghetti'}), confidence=0.3989145183175034, lift=2.291162176033379)]),
 RelationRecord(items=frozenset({'mineral water', 'herb & pepper'}), support=0.017064391414478068, ordered_statistics=[OrderedStatistic(items_base=frozenset({'herb & pepper'}), items_add=frozenset({'mineral water'}), confidence=0.34501347708894875, lift=1.447397142977743)]),
 RelationRecord(items=frozenset({'herb & pepper', 'spaghetti'}), support=0.01626449806692441, ordered_statistics=[OrderedStatistic(items_base=frozenset({'herb & pepper'}), items_add=frozenset({'spaghetti'}), confidence=0.32884097035040427, lift=1.8886953434903389)]),
 RelationRecord(items=frozenset({'mineral water', 'honey'}), support=0.015064658045593921, ordered_statistics=[OrderedStatistic(items_base=frozenset({'honey'}), items_add=frozenset({'mineral water'}), confidence=0.31741573033707865, lift=1.3316193474599705)]),
 RelationRecord(items=frozenset({'mineral water', 'low fat yogurt'}), support=0.023996800426609784, ordered_statistics=[OrderedStatistic(items_base=frozenset({'low fat yogurt'}), items_add=frozenset({'mineral water'}), confidence=0.313588850174216, lift=1.315564857470243)]),
 RelationRecord(items=frozenset({'milk', 'mineral water'}), support=0.04799360085321957, ordered_statistics=[OrderedStatistic(items_base=frozenset({'milk'}), items_add=frozenset({'mineral water'}), confidence=0.3703703703703704, lift=1.5537741320739085)]),
 RelationRecord(items=frozenset({'milk', 'soup'}), support=0.015197973603519531, ordered_statistics=[OrderedStatistic(items_base=frozenset({'soup'}), items_add=frozenset({'milk'}), confidence=0.3007915567282322, lift=2.3212319619531585)]),
 RelationRecord(items=frozenset({'mineral water', 'olive oil'}), support=0.027596320490601255, ordered_statistics=[OrderedStatistic(items_base=frozenset({'olive oil'}), items_add=frozenset({'mineral water'}), confidence=0.4190283400809717, lift=1.7579035676439423)]),
 RelationRecord(items=frozenset({'mineral water', 'pancakes'}), support=0.03372883615517931, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pancakes'}), items_add=frozenset({'mineral water'}), confidence=0.3548387096774194, lift=1.4886158620191963)]),
 RelationRecord(items=frozenset({'mineral water', 'red wine'}), support=0.010931875749900012, ordered_statistics=[OrderedStatistic(items_base=frozenset({'red wine'}), items_add=frozenset({'mineral water'}), confidence=0.38862559241706157, lift=1.6303582599107265)]),
 RelationRecord(items=frozenset({'mineral water', 'salmon'}), support=0.017064391414478068, ordered_statistics=[OrderedStatistic(items_base=frozenset({'salmon'}), items_add=frozenset({'mineral water'}), confidence=0.4012539184952978, lift=1.6833364891684726)]),
 RelationRecord(items=frozenset({'mineral water', 'shrimp'}), support=0.023596853752832957, ordered_statistics=[OrderedStatistic(items_base=frozenset({'shrimp'}), items_add=frozenset({'mineral water'}), confidence=0.3302238805970149, lift=1.385351973354703)]),
 RelationRecord(items=frozenset({'mineral water', 'soup'}), support=0.023063591521130515, ordered_statistics=[OrderedStatistic(items_base=frozenset({'soup'}), items_add=frozenset({'mineral water'}), confidence=0.45646437994722955, lift=1.9149548735929356)]),
 RelationRecord(items=frozenset({'mineral water', 'spaghetti'}), support=0.05972536995067324, ordered_statistics=[OrderedStatistic(items_base=frozenset({'spaghetti'}), items_add=frozenset({'mineral water'}), confidence=0.3430321592649311, lift=1.4390851379453289)]),
 RelationRecord(items=frozenset({'mineral water', 'tomatoes'}), support=0.024396747100386616, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tomatoes'}), items_add=frozenset({'mineral water'}), confidence=0.3567251461988304, lift=1.4965298219448695)]),
 RelationRecord(items=frozenset({'mineral water', 'turkey'}), support=0.019197440341287828, ordered_statistics=[OrderedStatistic(items_base=frozenset({'turkey'}), items_add=frozenset({'mineral water'}), confidence=0.3070362473347548, lift=1.288075442538029)]),
 RelationRecord(items=frozenset({'mineral water', 'whole wheat rice'}), support=0.020130649246767097, ordered_statistics=[OrderedStatistic(items_base=frozenset({'whole wheat rice'}), items_add=frozenset({'mineral water'}), confidence=0.3439635535307517, lift=1.4429925140012128)]),
 RelationRecord(items=frozenset({'olive oil', 'spaghetti'}), support=0.022930275963204905, ordered_statistics=[OrderedStatistic(items_base=frozenset({'olive oil'}), items_add=frozenset({'spaghetti'}), confidence=0.3481781376518219, lift=1.999758201015556)]),
 RelationRecord(items=frozenset({'spaghetti', 'red wine'}), support=0.010265297960271964, ordered_statistics=[OrderedStatistic(items_base=frozenset({'red wine'}), items_add=frozenset({'spaghetti'}), confidence=0.36492890995260663, lift=2.095966120638976)]),
 RelationRecord(items=frozenset({'spaghetti', 'salmon'}), support=0.013464871350486601, ordered_statistics=[OrderedStatistic(items_base=frozenset({'salmon'}), items_add=frozenset({'spaghetti'}), confidence=0.3166144200626959, lift=1.8184722548930183)]),
 RelationRecord(items=frozenset({'tomatoes', 'spaghetti'}), support=0.020930542594320756, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tomatoes'}), items_add=frozenset({'spaghetti'}), confidence=0.3060428849902534, lift=1.7577547322449394)]),
 RelationRecord(items=frozenset({'eggs', 'chocolate', 'mineral water'}), support=0.013464871350486601, ordered_statistics=[OrderedStatistic(items_base=frozenset({'eggs', 'chocolate'}), items_add=frozenset({'mineral water'}), confidence=0.40562248995983935, lift=1.7016634771749188)]),
 RelationRecord(items=frozenset({'eggs', 'chocolate', 'spaghetti'}), support=0.010531929076123183, ordered_statistics=[OrderedStatistic(items_base=frozenset({'eggs', 'chocolate'}), items_add=frozenset({'spaghetti'}), confidence=0.3172690763052209, lift=1.8222322675080107)]),
 RelationRecord(items=frozenset({'mineral water', 'chocolate', 'ground beef'}), support=0.010931875749900012, ordered_statistics=[OrderedStatistic(items_base=frozenset({'chocolate', 'ground beef'}), items_add=frozenset({'mineral water'}), confidence=0.47398843930635837, lift=1.988471634920019)]),
 RelationRecord(items=frozenset({'milk', 'chocolate', 'mineral water'}), support=0.013998133582189041, ordered_statistics=[OrderedStatistic(items_base=frozenset({'milk', 'chocolate'}), items_add=frozenset({'mineral water'}), confidence=0.43568464730290457, lift=1.827779943746693)]),
 RelationRecord(items=frozenset({'milk', 'chocolate', 'spaghetti'}), support=0.010931875749900012, ordered_statistics=[OrderedStatistic(items_base=frozenset({'milk', 'chocolate'}), items_add=frozenset({'spaghetti'}), confidence=0.34024896265560167, lift=1.954217051209547), OrderedStatistic(items_base=frozenset({'milk', 'spaghetti'}), items_add=frozenset({'chocolate'}), confidence=0.3082706766917293, lift=1.8814795328435)]),
 RelationRecord(items=frozenset({'mineral water', 'chocolate', 'spaghetti'}), support=0.01586455139314758, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mineral water', 'chocolate'}), items_add=frozenset({'spaghetti'}), confidence=0.3012658227848101, lift=1.7303177157035687), OrderedStatistic(items_base=frozenset({'chocolate', 'spaghetti'}), items_add=frozenset({'mineral water'}), confidence=0.40476190476190477, lift=1.6980531586236285)]),
 RelationRecord(items=frozenset({'eggs', 'ground beef', 'mineral water'}), support=0.010131982402346354, ordered_statistics=[OrderedStatistic(items_base=frozenset({'eggs', 'ground beef'}), items_add=frozenset({'mineral water'}), confidence=0.5066666666666667, lift=2.125563012677107)]),
 RelationRecord(items=frozenset({'eggs', 'milk', 'mineral water'}), support=0.013064924676709772, ordered_statistics=[OrderedStatistic(items_base=frozenset({'eggs', 'milk'}), items_add=frozenset({'mineral water'}), confidence=0.42424242424242425, lift=1.7797776421937497)]),
 RelationRecord(items=frozenset({'eggs', 'spaghetti', 'mineral water'}), support=0.014264764698040262, ordered_statistics=[OrderedStatistic(items_base=frozenset({'eggs', 'spaghetti'}), items_add=frozenset({'mineral water'}), confidence=0.3905109489051095, lift=1.6382676888910663)]),
 RelationRecord(items=frozenset({'mineral water', 'spaghetti', 'french fries'}), support=0.010131982402346354, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mineral water', 'french fries'}), items_add=frozenset({'spaghetti'}), confidence=0.30039525691699603, lift=1.7253176279742628), OrderedStatistic(items_base=frozenset({'spaghetti', 'french fries'}), items_add=frozenset({'mineral water'}), confidence=0.36714975845410625, lift=1.54026305266457)]),
 RelationRecord(items=frozenset({'milk', 'mineral water', 'frozen vegetables'}), support=0.011065191307825623, ordered_statistics=[OrderedStatistic(items_base=frozenset({'milk', 'frozen vegetables'}), items_add=frozenset({'mineral water'}), confidence=0.46892655367231634, lift=1.9672360621342533), OrderedStatistic(items_base=frozenset({'mineral water', 'frozen vegetables'}), items_add=frozenset({'milk'}), confidence=0.3097014925373134, lift=2.3899906332534853)]),
 RelationRecord(items=frozenset({'mineral water', 'spaghetti', 'frozen vegetables'}), support=0.011998400213304892, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mineral water', 'frozen vegetables'}), items_add=frozenset({'spaghetti'}), confidence=0.33582089552238803, lift=1.9287844849260587), OrderedStatistic(items_base=frozenset({'spaghetti', 'frozen vegetables'}), items_add=frozenset({'mineral water'}), confidence=0.43062200956937796, lift=1.806541215760573)]),
 RelationRecord(items=frozenset({'milk', 'ground beef', 'mineral water'}), support=0.011065191307825623, ordered_statistics=[OrderedStatistic(items_base=frozenset({'milk', 'ground beef'}), items_add=frozenset({'mineral water'}), confidence=0.503030303030303, lift=2.1103077757440176)]),
 RelationRecord(items=frozenset({'mineral water', 'spaghetti', 'ground beef'}), support=0.017064391414478068, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mineral water', 'ground beef'}), items_add=frozenset({'spaghetti'}), confidence=0.41693811074918563, lift=2.3946805273580716), OrderedStatistic(items_base=frozenset({'spaghetti', 'ground beef'}), items_add=frozenset({'mineral water'}), confidence=0.4353741496598639, lift=1.8264773470909614)]),
 RelationRecord(items=frozenset({'milk', 'spaghetti', 'mineral water'}), support=0.01573123583522197, ordered_statistics=[OrderedStatistic(items_base=frozenset({'milk', 'mineral water'}), items_add=frozenset({'spaghetti'}), confidence=0.3277777777777778, lift=1.882588905904373), OrderedStatistic(items_base=frozenset({'milk', 'spaghetti'}), items_add=frozenset({'mineral water'}), confidence=0.44360902255639095, lift=1.8610242048073202)]),
 RelationRecord(items=frozenset({'mineral water', 'olive oil', 'spaghetti'}), support=0.010265297960271964, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mineral water', 'olive oil'}), items_add=frozenset({'spaghetti'}), confidence=0.3719806763285024, lift=2.13646788142427), OrderedStatistic(items_base=frozenset({'olive oil', 'spaghetti'}), items_add=frozenset({'mineral water'}), confidence=0.4476744186046512, lift=1.8780793142916603)]),
 RelationRecord(items=frozenset({'mineral water', 'spaghetti', 'pancakes'}), support=0.011465137981602452, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mineral water', 'pancakes'}), items_add=frozenset({'spaghetti'}), confidence=0.33992094861660077, lift=1.9523331053392974), OrderedStatistic(items_base=frozenset({'spaghetti', 'pancakes'}), items_add=frozenset({'mineral water'}), confidence=0.455026455026455, lift=1.908922505119373)])]

### Putting the results well organised into a Pandas DataFrame

In [28]:
res = results[1]
res.ordered_statistics.items_base

[OrderedStatistic(items_base=frozenset({'burgers'}), items_add=frozenset({'eggs'}), confidence=0.33027522935779813, lift=1.8378297443715457)]

In [14]:
results[1]

RelationRecord(items=frozenset({'burgers', 'eggs'}), support=0.02879616051193174, ordered_statistics=[OrderedStatistic(items_base=frozenset({'burgers'}), items_add=frozenset({'eggs'}), confidence=0.33027522935779813, lift=1.8378297443715457)])

In [ ]:
def inspect(results):
    lhs = [tuple(result[2][0][0])[0] for result in results]
    rhs = [tuple(result[2][0][1])[0] for result in results]
    supports = [result[1] for result in results]
    confidences = [result[2][0][2] for result in results]
    lifts = [result[2][0][3] for result in results]
    return list(zip(lhs, rhs, supports, confidences, lifts))


resultsinDataFrame = pd.DataFrame(inspect(results),
                                  columns=['Left Hand Side', 'Right Hand Side', 'Support', 'Confidence', 'Lift'])

### Displaying the results non sorted

In [ ]:
resultsinDataFrame

       Left Hand Side Right Hand Side   Support  Confidence      Lift
0             avocado   mineral water  0.011598    0.348000  1.459926
1             burgers            eggs  0.028796    0.330275  1.837830
2                cake   mineral water  0.027463    0.338816  1.421397
3             cereals   mineral water  0.010265    0.398964  1.673729
4             chicken   mineral water  0.022797    0.380000  1.594172
5           chocolate   mineral water  0.052660    0.321400  1.348332
6         cooking oil   mineral water  0.020131    0.394256  1.653978
7         cooking oil       spaghetti  0.015865    0.310705  1.784531
8              turkey            eggs  0.019464    0.311301  1.732245
9         fresh bread   mineral water  0.013332    0.309598  1.298820
10    frozen smoothie   mineral water  0.020264    0.320000  1.342461
11  frozen vegetables   mineral water  0.035729    0.374825  1.572463
12      grated cheese   mineral water  0.017464    0.333333  1.398397
13      grated cheese       spaghetti  0.016531    0.315522  1.812196
14      herb & pepper     ground beef  0.015998    0.323450  3.291994
15        ground beef   mineral water  0.040928    0.416554  1.747522
16        ground beef       spaghetti  0.039195    0.398915  2.291162
17      herb & pepper   mineral water  0.017064    0.345013  1.447397
18      herb & pepper       spaghetti  0.016264    0.328841  1.888695
19              honey   mineral water  0.015065    0.317416  1.331619
20     low fat yogurt   mineral water  0.023997    0.313589  1.315565
21               milk   mineral water  0.047994    0.370370  1.553774
22               soup            milk  0.015198    0.300792  2.321232
23          olive oil   mineral water  0.027596    0.419028  1.757904
24           pancakes   mineral water  0.033729    0.354839  1.488616
25           red wine   mineral water  0.010932    0.388626  1.630358
26             salmon   mineral water  0.017064    0.401254  1.683336
27             shrimp   mineral water  0.023597    0.330224  1.385352
28               soup   mineral water  0.023064    0.456464  1.914955
29          spaghetti   mineral water  0.059725    0.343032  1.439085
30           tomatoes   mineral water  0.024397    0.356725  1.496530
31             turkey   mineral water  0.019197    0.307036  1.288075
32   whole wheat rice   mineral water  0.020131    0.343964  1.442993
33          olive oil       spaghetti  0.022930    0.348178  1.999758
34           red wine       spaghetti  0.010265    0.364929  2.095966
35             salmon       spaghetti  0.013465    0.316614  1.818472
36           tomatoes       spaghetti  0.020931    0.306043  1.757755
37          chocolate   mineral water  0.013465    0.405622  1.701663
38          chocolate       spaghetti  0.010532    0.317269  1.822232
39          chocolate   mineral water  0.010932    0.473988  1.988472
40          chocolate   mineral water  0.013998    0.435685  1.827780
41          chocolate       spaghetti  0.010932    0.340249  1.954217
42          chocolate       spaghetti  0.015865    0.301266  1.730318
43        ground beef   mineral water  0.010132    0.506667  2.125563
44               milk   mineral water  0.013065    0.424242  1.779778
45          spaghetti   mineral water  0.014265    0.390511  1.638268
46      mineral water       spaghetti  0.010132    0.300395  1.725318
47  frozen vegetables   mineral water  0.011065    0.468927  1.967236
48      mineral water       spaghetti  0.011998    0.335821  1.928784
49        ground beef   mineral water  0.011065    0.503030  2.110308
50        ground beef       spaghetti  0.017064    0.416938  2.394681
51      mineral water       spaghetti  0.015731    0.327778  1.882589
52      mineral water       spaghetti  0.010265    0.371981  2.136468
53           pancakes       spaghetti  0.011465    0.339921  1.952333

### Displaying the results sorted by descending lifts

In [ ]:
resultsinDataFrame.nlargest(n=10, columns='Lift')

   Left Hand Side Right Hand Side   Support  Confidence      Lift
14  herb & pepper     ground beef  0.015998    0.323450  3.291994
50    ground beef       spaghetti  0.017064    0.416938  2.394681
22           soup            milk  0.015198    0.300792  2.321232
16    ground beef       spaghetti  0.039195    0.398915  2.291162
52  mineral water       spaghetti  0.010265    0.371981  2.136468
43    ground beef   mineral water  0.010132    0.506667  2.125563
49    ground beef   mineral water  0.011065    0.503030  2.110308
34       red wine       spaghetti  0.010265    0.364929  2.095966
33      olive oil       spaghetti  0.022930    0.348178  1.999758
39      chocolate   mineral water  0.010932    0.473988  1.988472