In [3]:
from ucimlrepo import fetch_ucirepo

# Загружаем датасет
apartment_for_rent_classified = fetch_ucirepo(id=555)

# Данные в виде pandas DataFrame
X = apartment_for_rent_classified.data.features
y = apartment_for_rent_classified.data.targets

# Метаданные
print(apartment_for_rent_classified.metadata)

# Информация о переменных
print(apartment_for_rent_classified.variables)

{'uci_id': 555, 'name': 'Apartment for Rent Classified', 'repository_url': 'https://archive.ics.uci.edu/dataset/555/apartment+for+rent+classified', 'data_url': 'https://archive.ics.uci.edu/static/public/555/data.csv', 'abstract': 'This is a dataset of classified for apartments for rent in USA.\n', 'area': 'Business', 'tasks': ['Classification', 'Regression', 'Clustering'], 'characteristics': ['Multivariate'], 'num_instances': 10000, 'num_features': 21, 'feature_types': ['Categorical', 'Integer'], 'demographics': [], 'target_col': None, 'index_col': ['id'], 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2019, 'last_updated': 'Mon Feb 26 2024', 'dataset_doi': '10.24432/C5X623', 'creators': [], 'intro_paper': None, 'additional_info': {'summary': "The dataset contains of 10'000 or 100'000 rows and of 22 columns The data has been cleaned in the way that \r\ncolumn price and square_feet never is empty but the dataset is saved as it was created.\r\n\r\nCan be used for different machine learning tasks such as clustering, classification and also regression for the squares feet column", 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'id = unique identifier of apartment\ncategory = category of classified\ntitle = title text of apartment\nbody = body text of apartment\namenities = like AC, basketball,cable, gym, internet access, pool, refrigerator etc.\nbathrooms = number of bathrooms\nbedrooms = number of bedrooms\ncurrency = price in current\nfee = fee\nhas_photo = photo of apartment\npets_allowed = what pets are allowed dogs/cats etc.\nprice = rental price of apartment\nprice_display = price converted into display for reader\nprice_type = price in USD\nsquare_feet = size of the apartment\naddress =  where the apartment is located\ncityname =  where the apartment is located\nstate =  where the apartment is located\nlatitude = where the apartment is located\nlongitude = where the apartment is located\nsource = origin of classified\ntime = when classified was created', 'citation': None}}
             name     role         type demographic description units  \
0              id       ID      Integer        None        None  None
1        category  Feature  Categorical        None        None  None
2           title  Feature  Categorical        None        None  None
3            body  Feature  Categorical        None        None  None
4       amenities  Feature  Categorical        None        None  None
5       bathrooms  Feature      Integer        None        None  None
6        bedrooms  Feature  Categorical        None        None  None
7        currency  Feature  Categorical        None        None  None
8             fee  Feature  Categorical        None        None  None
9       has_photo  Feature  Categorical        None        None  None
10   pets_allowed  Feature  Categorical        None        None  None
11          price  Feature      Integer        None        None  None
12  price_display  Feature      Integer        None        None  None
13     price_type  Feature  Categorical        None        None  None
14    square_feet  Feature  Categorical        None        None  None
15        address  Feature  Categorical        None        None  None
16       cityname  Feature  Categorical        None        None  None
17          state  Feature      Integer        None        None  None
18       latitude  Feature      Integer        None        None  None
19      longitude  Feature  Categorical        None        None  None
20         source  Feature      Integer        None        None  None
21           time  Feature  Categorical        None        None  None

   missing_values
0              no
1              no
2              no
3              no
4              no
5              no
6              no
7              no
8              no
9              no
10             no
11             no
12             no
13             no
14             no
15             no
16             no
17             no
18             no
19             no
20             no
21             no

/Users/user/AI_Project/.venv/lib/python3.9/site-packages/ucimlrepo/fetch.py:97: DtypeWarning: Columns (0,5,6,12,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(data_url)

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
df = X.copy()

In [18]:
df.head()
df

,category,title,body,amenities,bathrooms,bedrooms,currency,fee,has_photo,pets_allowed,price,price_type,square_feet,address,cityname,state,latitude,longitude,source,time
0,housing/rent/apartment,One BR 507 & 509 Esplanade,"This unit is located at 507 & 509 Esplanade, R...",NaN,1,1,USD,No,Thumbnail,1,2195.0,Monthly,542,507 509 Esplanade,Redondo Beach,CA,33.8520,-118.3759,RentLingo,1.577360e+09
1,housing/rent/apartment,Three BR 146 Lochview Drive,"This unit is located at 146 Lochview Drive, Ne...",NaN,1.5,3,USD,No,Thumbnail,1,1250.0,Monthly,1500,146 Lochview Dr,Newport News,VA,37.0867,-76.4941,RentLingo,1.577360e+09
2,housing/rent/apartment,Three BR 3101 Morningside Drive,This unit is located at 3101 Morningside Drive...,NaN,2,3,USD,No,Thumbnail,0,1395.0,Monthly,1650,3101 Morningside Dr,Raleigh,NC,35.8230,-78.6438,RentLingo,1.577360e+09
3,housing/rent/apartment,Two BR 209 Aegean Way,"This unit is located at 209 Aegean Way, Vacavi...",NaN,1,2,USD,No,Thumbnail,1,1600.0,Monthly,820,209 Aegean Way,Vacaville,CA,38.3622,-121.9712,RentLingo,1.577360e+09
4,housing/rent/apartment,One BR 4805 Marquette NE,"This unit is located at 4805 Marquette NE, Alb...",NaN,1,1,USD,No,Thumbnail,1,975.0,Monthly,624,4805 Marquette NE,Albuquerque,NM,35.1038,-106.6110,RentLingo,1.577360e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99821,housing/rent/apartment,Houston - superb Apartment nearby fine dining,"Redefining urban living, in southeast Houston,...","Gym,Parking,Patio/Deck,Playground,Storage,Wood...",1.0,1.0,USD,No,Yes,0,780.0,Monthly,605,NaN,Houston,TX,29.6151,-95.1998,RentDigs.com,1.544186e+09
99822,housing/rent/apartment,The Best of the Best in the City of Jacksonvil...,Courtney Manor Apartments offer the best of ev...,"AC,Cable or Satellite,Clubhouse,Dishwasher,Gym...",2.0,2.0,USD,No,Yes,1,813.0,Monthly,921,NaN,Jacksonville,FL,30.2254,-81.7579,RentDigs.com,1.544186e+09
99823,housing/rent/apartment,A great & large One BR apartment. Pet OK!,"Fully remodeled, new floor, kitchen cabinet, s...","Garbage Disposal,Refrigerator",1.0,1.0,USD,No,Yes,1,1325.0,Monthly,650,NaN,San Diego,CA,32.7379,-117.0914,RentDigs.com,1.544186e+09
99824,housing/rent/apartment,"The Crest offers studio, 1, 2 & Three BR homes...","Amenities include a fitness facilities, swimmi...","Gym,Pool",1.0,1.0,USD,No,Yes,1,931.0,Monthly,701,NaN,Huntersville,NC,35.4158,-80.8451,RentDigs.com,1.544186e+09
99825,housing/rent/apartment,Large Remodeled Two BR 1. Five BA Apartment Home,This is a brand new 2 Beds 1. five Bathrooms A...,"Gated,Parking,Wood Floors",1.5,2.0,USD,No,Yes,0,1595.0,Monthly,900,NaN,San Diego,CA,32.7379,-117.0914,RentDigs.com,1.544186e+09

In [10]:
# general information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99826 entries, 0 to 99825
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   category       99826 non-null  object
 1   title          99826 non-null  object
 2   body           99826 non-null  object
 3   amenities      83749 non-null  object
 4   bathrooms      99760 non-null  object
 5   bedrooms       99699 non-null  object
 6   currency       99822 non-null  object
 7   fee            99823 non-null  object
 8   has_photo      99823 non-null  object
 9   pets_allowed   39192 non-null  object
 10  price          99821 non-null  float64
 11  price_display  99820 non-null  object
 12  price_type     99823 non-null  object
 13  square_feet    99823 non-null  object
 14  address        7946 non-null   object
 15  cityname       99521 non-null  object
 16  state          99521 non-null  object
 17  latitude       99797 non-null  float64
 18  longitude      99795 non-null  float64
 19  source         99820 non-null  object
 20  time           99820 non-null  float64
dtypes: float64(4), object(17)
memory usage: 16.0+ MB

In [11]:
df.isna().sum()/len(df)*100

category          0.000000
title             0.000000
body              0.000000
amenities        16.105023
bathrooms         0.066115
bedrooms          0.127221
currency          0.004007
fee               0.003005
has_photo         0.003005
pets_allowed     60.739687
price             0.005009
price_display     0.006010
price_type        0.003005
square_feet       0.003005
address          92.040150
cityname          0.305532
state             0.305532
latitude          0.029051
longitude         0.031054
source            0.006010
time              0.006010
dtype: float64

In [12]:
df[['price','price_display']]
# price_display ni tashlab yuborsa b-di

        price price_display
0      2195.0          2195
1      1250.0          1250
2      1395.0          1395
3      1600.0          1600
4       975.0           975
...       ...           ...
99821   780.0           780
99822   813.0           813
99823  1325.0          1325
99824   931.0           931
99825  1595.0          1595

[99826 rows x 2 columns]

In [13]:
cols=['bathrooms','bedrooms','price']
df.dropna(subset=cols, inplace=True)
df[cols].isna().sum()

bathrooms    0
bedrooms     0
price        0
dtype: int64

In [14]:
df['pets_allowed']=X['pets_allowed'].fillna('None')
df['pets_allowed']=np.where(df['pets_allowed']=='None',0,1)
df['pets_allowed'].head()
#df['pets_allowed'].isna().sum()

0    1
1    1
2    0
3    1
4    1
Name: pets_allowed, dtype: int64

In [15]:
# price_displayni tashlab yuboramiz
df=df.drop('price_display',axis=1)

In [19]:
df['currency'].unique()
# currency nii tashlab yuboramiz sabab faqat 1 dona variable bor
df=df.drop('currency',axis=1)

# CITY, State, Latitude, Longitude

In [20]:
df.loc[df['cityname'].isna() | df['state'].isna(), ['longitude', 'latitude']].value_counts()

longitude  latitude
-98.5576   39.8163     217
-75.9597   37.2770      16
-92.2006   37.8286      15
-78.9348   35.4164       7
-78.3960   36.3540       7
-78.1713   36.4861       4
-122.6052  38.7904       3
-78.3435   35.6032       2
-117.2430  34.2143       1
-82.1971   28.4590       1
Name: count, dtype: int64

In [21]:
df.loc[((df['cityname'].isna()) | (df['state'].isna())) & (df['longitude']==-98.5576), 'cityname'] = 'Lebanon'
df.loc[((df['cityname'].isna()) | (df['state'].isna())) & (df['longitude']==-98.5576), 'state'] = 'KS'
df.loc[((df['cityname'].isna()) | (df['state'].isna())) & (df['longitude']==-75.9597), 'cityname'] = 'Cape Charles'
df.loc[((df['cityname'].isna()) | (df['state'].isna())) & (df['longitude']==-75.9597), 'state'] = 'VA'
df.loc[((df['cityname'].isna()) | (df['state'].isna())) & (df['longitude']==-92.2006), 'cityname'] = 'Waynesville'
df.loc[((df['cityname'].isna()) | (df['state'].isna())) & (df['longitude']==-92.2006), 'state'] = 'MO'

df = df.dropna(subset=['cityname', 'state'])
df[['cityname', 'state']].isna().sum()

cityname    0
state       0
dtype: int64

In [22]:
df.isna().sum()

category            0
title               0
body                0
amenities       15979
bathrooms           0
bedrooms            0
fee                 0
has_photo           0
pets_allowed        0
price               0
price_type          0
square_feet         0
address         91689
cityname            0
state               0
latitude            0
longitude           2
source              2
time                2
dtype: int64

In [23]:
df['address'].head(10)
df['address'].nunique()
# address ni drop qilamiz sabab, bizda koordinates bor
df=df.drop('address',axis=1)

In [25]:
df['amenities'].nunique()

9820

In [26]:
print('top10',df['amenities'].value_counts().head(10))
print('-'*50)
print("last 10", df['amenities'].value_counts().tail(10))

top10 amenities
Parking               6194
Parking,Storage       2116
Gym,Pool              1875
Pool                  1481
Gym,Parking,Pool      1191
Parking,Pool           888
Washer Dryer           839
Patio/Deck             775
Clubhouse,Gym,Pool     767
Gym                    742
Name: count, dtype: int64
--------------------------------------------------
last 10 amenities
Clubhouse,Gym,Patio/Deck,Pool,Storage,Tennis                                                                               1
Cable or Satellite,Dishwasher,Gym,Internet Access,Refrigerator,Storage,TV,Washer Dryer,Wood Floors                         1
Elevator,Gated,Parking,Wood Floors                                                                                         1
AC,Cable or Satellite,Dishwasher,Fireplace,Garbage Disposal,Patio/Deck,Refrigerator,Tennis,Washer Dryer                    1
Gated,Parking,Pool,Washer Dryer,Wood Floors                                                                                1
Basketball,Clubhouse,Dishwasher,Fireplace,Gated,Patio/Deck,Playground,Pool,Refrigerator,Tennis,Washer Dryer,Wood Floors    1
AC,Cable or Satellite,Elevator,Gym,Internet Access,Refrigerator,TV,Wood Floors                                             1
AC,Gated,Parking,Refrigerator,Storage,Washer Dryer                                                                         1
AC,Dishwasher,Garbage Disposal,Patio/Deck,Storage,Washer Dryer,Wood Floors                                                 1
Dishwasher,Doorman,Patio/Deck,Refrigerator,Storage,Washer Dryer,Wood Floors                                                1
Name: count, dtype: int64

In [27]:
df['amenities']

0                                                      NaN
1                                                      NaN
2                                                      NaN
3                                                      NaN
4                                                      NaN
                               ...
99821    Gym,Parking,Patio/Deck,Playground,Storage,Wood...
99822    AC,Cable or Satellite,Clubhouse,Dishwasher,Gym...
99823                        Garbage Disposal,Refrigerator
99824                                             Gym,Pool
99825                            Gated,Parking,Wood Floors
Name: amenities, Length: 99585, dtype: object

In [29]:
def classify_listing(amenities):
    luxury_amenities = {
        "Gym", "Pool", "Clubhouse", "Hot Tub",
        "Doorman", "Gated", "View",
        "Tennis", "Elevator", "Fireplace",
        "Basketball Court", "Basketball", "Playground", "Hot Tub",'luxury'
    }
    # Split and strip the amenities, and create a set
    amenities_set = set(amenity.strip() for amenity in amenities.split(','))

    # Check for any intersection with luxury amenities
    if amenities_set & luxury_amenities:
        return "luxury"
    else:
        return "basic"

In [31]:
df['amenities']=df['amenities'].fillna('basic')

In [32]:
df['amenities'].isna().sum()

np.int64(0)

In [35]:

df['amenities']=df['amenities'].apply(classify_listing)
df['amenities'].value_counts()

amenities
luxury    60260
basic     39325
Name: count, dtype: int64

In [36]:
df.isna().sum()

category        0
title           0
body            0
amenities       0
bathrooms       0
bedrooms        0
fee             0
has_photo       0
pets_allowed    0
price           0
price_type      0
square_feet     0
cityname        0
state           0
latitude        0
longitude       2
source          2
time            2
dtype: int64

In [43]:
df=df.drop(['id','title','body'],axis=1)
df.head()

KeyError: "['id'] not found in axis"

# Categorical ni numerical ga convert qilamiz

In [45]:
df['category'].value_counts()

category
housing/rent/apartment            99523
housing/rent/commercial/retail       42
housing/rent                          7
housing/rent/home                     4
housing/rent/short_term               3
housing/rent/condo                    3
Gym                                   1
Parking,Patio/Deck                    1
housing/rent/other                    1
Name: count, dtype: int64

In [46]:
df['category'].value_counts()
df['category']=np.where((df['category']=="housing/rent/apartment")|(df['category']=="housing/rent/home"),'living','business')

In [48]:
df['category']=np.where(df['category']=='living',1,0)

# 1 means apartment or home
# 0 means other purposes

In [49]:
df['amenities']=np.where(df['amenities']=='basic',1,0)

# 1 means it has basic needs,
# 0 means it is luxury house

In [52]:
df['fee'].value_counts()
df['fee']=np.where(df['fee']=='Yes',1,0)

# 1 means there is an initial payment
# 0 means there is not an initial payment

In [50]:
df['has_photo'].value_counts()
df['has_photo']=np.where(df['has_photo']=='No',0,1)

# 1 means there is a photo
# 0 means there is not a photo

In [53]:
df.head()

,category,amenities,bathrooms,bedrooms,fee,has_photo,pets_allowed,price,price_type,square_feet,cityname,state,latitude,longitude,source,time
0,0,1,1,1,0,1,1,2195.0,Monthly,542,Redondo Beach,CA,33.8520,-118.3759,RentLingo,1.577360e+09
1,0,1,1.5,3,0,1,1,1250.0,Monthly,1500,Newport News,VA,37.0867,-76.4941,RentLingo,1.577360e+09
2,0,1,2,3,0,1,0,1395.0,Monthly,1650,Raleigh,NC,35.8230,-78.6438,RentLingo,1.577360e+09
3,0,1,1,2,0,1,1,1600.0,Monthly,820,Vacaville,CA,38.3622,-121.9712,RentLingo,1.577360e+09
4,0,1,1,1,0,1,1,975.0,Monthly,624,Albuquerque,NM,35.1038,-106.6110,RentLingo,1.577360e+09

In [55]:
df['price_type'].value_counts()
# weekly paymentni monthly ga change qilish ucun
# weekly paymentni 4 ga multiply qilishimiz kerak
# keyin price type ni tashlab yuborsak b-di
# mask=df['price_type'].isin(['Weekly'])

price_type
Monthly        99580
Weekly             3
Lawrence           1
Los Angeles        1
Name: count, dtype: int64

In [56]:
df.loc[mask,'price']=df.loc[mask,'price']*4.3

In [57]:
# Now we can drop column price_type
df=df.drop('price_type',axis=1)

In [58]:
df.head()

,category,amenities,bathrooms,bedrooms,fee,has_photo,pets_allowed,price,square_feet,cityname,state,latitude,longitude,source,time
0,0,1,1,1,0,1,1,2195.0,542,Redondo Beach,CA,33.8520,-118.3759,RentLingo,1.577360e+09
1,0,1,1.5,3,0,1,1,1250.0,1500,Newport News,VA,37.0867,-76.4941,RentLingo,1.577360e+09
2,0,1,2,3,0,1,0,1395.0,1650,Raleigh,NC,35.8230,-78.6438,RentLingo,1.577360e+09
3,0,1,1,2,0,1,1,1600.0,820,Vacaville,CA,38.3622,-121.9712,RentLingo,1.577360e+09
4,0,1,1,1,0,1,1,975.0,624,Albuquerque,NM,35.1038,-106.6110,RentLingo,1.577360e+09

# Source
* 1 represents RentDigs.com or RentLingo
* 0 represents other sources

In [59]:

df['source']=np.where((df['source']=='RentDigs.com')|(df['source']=='RentLingo'),1,0)
df['source'].value_counts()

source
1    97966
0     1619
Name: count, dtype: int64

In [60]:
df.drop(['cityname','state'],axis=1).corr()

ValueError: could not convert string to float: 'No'

In [6]:
from sklearn.preprocessing import OneHotEncoder

In [61]:
encoder=OneHotEncoder()

NameError: name 'OneHotEncoder' is not defined

In [62]:
df[['state']].value_counts()

state
TX              11258
CA              10284
VA               8318
NC               6307
CO               6285
FL               5781
MD               5305
MA               5037
OH               4908
GA               4790
NJ               4494
NV               2815
WA               2617
AZ               2378
LA               1354
MO               1217
PA               1134
KS               1128
TN               1114
IL               1032
NE               1019
KY                994
OK                959
SC                908
UT                809
ND                740
NH                733
MI                709
NY                653
AR                598
MN                579
CT                513
IN                503
WI                428
IA                371
AL                352
OR                277
VT                125
RI                119
MS                107
ID                 96
MT                 88
SD                 86
DC                 83
AK                 57
HI                 31
ME                 30
NM                 24
WY                 16
WV                 13
DE                  7
RentDigs.com        2
Name: count, dtype: int64

In [ ]:
df['num_state']=encoder.fit_transform(df['state'].values.reshape(-1,1))

In [ ]:
df['num_state'].value_counts()

In [ ]:
df['num_city']=encoder.fit_transform(df['cityname'].values.reshape(-1,1))

In [ ]:
df.drop(['cityname','state'],axis=1).corr()['price']

In [ ]:
df.head()

In [ ]:
def time_convert(unix_time, ret='month'):
    import datetime
    dt_object = datetime.datetime.utcfromtimestamp(unix_time)
    if ret == 'month':
        return dt_object.month
    else:
        return dt_object.year

In [ ]:
df['month']=df['time'].apply(time_convert)
df['year']=df['time'].apply(time_convert, ret='year')
df.head()

In [ ]:
df=df.drop(['cityname','state','time'],axis=1)

In [ ]:
df.info()

In [ ]:
df['month'].value_counts()

In [ ]:
df['datetime']=pd.to_datetime(df['year'].astype(str) + '/'+df['month'].astype(str))
df.head()

In [ ]:
df=df.drop(['year','month'],axis=1)
df.head()

In [ ]:
df.corr()['price']

In [ ]:
from matplotlib import pyplot as plt

In [ ]:
df['datetime'].value_counts()

In [ ]:
import seaborn as sns

In [ ]:
sns.barplot(data=df.sort_values(by=['datetime']),x='datetime',y='price')
plt.xticks(rotation=90)
plt.show()

In [ ]:
df['price'].plot(kind='hist',bins=50)
plt.show()
# here we can see that price is highly right skewed
# we should treat it

In [ ]:
from scipy.stats import norm,poisson

In [ ]:
x=df['price'].sort_values()
y=norm.pdf(x,loc=x.mean(),scale=x.std())
plt.plot(x,y)
plt.show()

In [ ]:
sns.boxplot(data=df,x='price')
plt.show()

In [ ]:
## it is highly right skewed

In [ ]:
# 1st method with IQR
q1,q3=df['price'].quantile([0.25,0.75])
iqr=q3-q1
lower_bound=q1-1.5*iqr
upper_bound=q3+1.5*iqr
mask=(df['price']>=lower_bound) & (df['price']<=upper_bound)
df_new=df[mask]
x=df_new['price'].sort_values()
y=norm.pdf(x,loc=x.mean(),scale=x.std())
plt.plot(x,y)
plt.grid()
plt.show()

In [ ]:
df_new['price'].plot(kind='hist',bins=50)
plt.show()

In [ ]:
sns.boxplot(data=df_new,x='price')
plt.show()

In [ ]:
x=df_new['price'].sort_values()
y=norm.cdf(x,loc=x.mean(),scale=x.std())
plt.plot(x,y)
plt.grid()
plt.show()

In [ ]:
# 2nd method by using ML algorithm
from sklearn.ensemble import IsolationForest

In [ ]:
iso = IsolationForest(contamination=0.1)
y_pred = iso.fit_predict(df[['price']])

# Filter out outliers
df_no_outliers = df[y_pred == 1]

In [ ]:
x=df_no_outliers['price'].sort_values()
y=norm.pdf(x,loc=x.mean(),scale=x.std())
plt.plot(x,y)
plt.show()

In [ ]:
# 3rd method by using z-score
z=(df['price']-df['price'].mean())/df['price'].std()
mask=(z>=-3) & (z<=3)
df_no_out_z=df[mask]
x=df_no_out_z['price'].sort_values()
y=norm.pdf(x,loc=x.mean(),scale=x.std())
plt.plot(x,y)
plt.show()

In [ ]:
# we can choose 1st method
X=df_new.drop(['price','datetime'],axis=1)   # X is independent variables or features
y=df_new['price']   # y is dependant variable or target

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_percentage_error, mean_squared_error

linear_regression=LinearRegression()

In [ ]:
trainx,testx,trainy,testy=train_test_split(X,y,test_size=0.2,random_state=23)

In [ ]:
model=linear_regression.fit(trainx,trainy)
pred=model.predict(testx)
print("r2=",r2_score(testy,pred))
print('mape=',mean_absolute_percentage_error(testy,pred))
print('rmse=',np.sqrt(mean_squared_error(testy,pred)))

In [ ]:
plt.scatter(testy,pred)
plt.show()

In [ ]:
np.corrcoef(testy.values,pred)

In [ ]:
from sklearn.tree import DecisionTreeRegressor
decision_tree=DecisionTreeRegressor()

In [ ]:
model=decision_tree.fit(trainx,trainy)
pred=model.predict(testx)
print("r2=",r2_score(testy,pred))
print('mape=',mean_absolute_percentage_error(testy,pred))
print('rmse=',np.sqrt(mean_squared_error(testy,pred)))
plt.scatter(testy,pred)

In [ ]:
from xgboost import XGBRegressor
xgboost=XGBRegressor()

In [ ]:
model=xgboost.fit(trainx,trainy)
pred=model.predict(testx)
print("r2=",r2_score(testy,pred))
print('mape=',mean_absolute_percentage_error(testy,pred))
print('rmse=',np.sqrt(mean_squared_error(testy,pred)))
plt.scatter(testy,pred)

In [ ]:
from sklearn.ensemble import StackingRegressor
# Initialize the stacking model
stacking_model = StackingRegressor(
    estimators=[('dt', decision_tree), ('xgb', xgboost)],
    final_estimator=XGBRegressor()
)

In [ ]:
model=stacking_model.fit(trainx,trainy)
pred=model.predict(testx)
print("r2=",r2_score(testy,pred))
print('mape=',mean_absolute_percentage_error(testy,pred))
print('rmse=',np.sqrt(mean_squared_error(testy,pred)))
plt.scatter(testy,pred)
plt.show()

In [ ]:
from sklearn.ensemble import RandomForestRegressor
random_forest=RandomForestRegressor()

In [ ]:
model=random_forest.fit(trainx,trainy)
pred=model.predict(testx)
print("r2=",r2_score(testy,pred))
print('mape=',mean_absolute_percentage_error(testy,pred))
print('rmse=',np.sqrt(mean_squared_error(testy,pred)))
plt.scatter(testy,pred)

In [ ]:
stacking_model = StackingRegressor(
    estimators=[('rf', random_forest), ('xgb', xgboost)],
    final_estimator=XGBRegressor()
)

In [ ]:
model=stacking_model.fit(trainx,trainy)
pred=model.predict(testx)
print("r2=",r2_score(testy,pred))
print('mape=',mean_absolute_percentage_error(testy,pred))
print('rmse=',np.sqrt(mean_squared_error(testy,pred)))
plt.scatter(testy,pred)
plt.show()

In [ ]:
stacking_model = StackingRegressor(
    estimators=[('lr', linear_regression), ('xgb', xgboost)],
    final_estimator=XGBRegressor()
)

In [ ]:
model=stacking_model.fit(trainx,trainy)
pred=model.predict(testx)
print("r2=",r2_score(testy,pred))
print('mape=',mean_absolute_percentage_error(testy,pred))
print('rmse=',np.sqrt(mean_squared_error(testy,pred)))
plt.scatter(testy,pred)
plt.show()

In [ ]:
from sklearn.feature_selection import SelectKBest, mutual_info_regression

In [ ]:
df_new.columns

In [ ]:
df_for_test=df_new[['category','amenities','bathrooms','bedrooms','fee','has_photo','pets_allowed','source',"num_state",'num_city']]
xtrain,xtest,ytrain,ytest=train_test_split(df_for_test,y,test_size=0.2,random_state=9)

In [ ]:
# Apply mutual information for feature selection
mi_selector = SelectKBest(mutual_info_regression, k=3)
x_kbest = mi_selector.fit_transform(xtrain, ytrain)

# Display the scores for each feature
scores = mi_selector.scores_

print("Mutual Information scores:", scores)

# Select top features based on mutual information
k_best_features = mi_selector.get_support(indices=True)
selected_features = xtrain.columns[k_best_features]

print("Selected features:", selected_features)

In [ ]:
df_new.drop(columns=['category','amenities','bathrooms','bedrooms','fee','has_photo','pets_allowed','source',"num_state",'num_city']).corr()['price']

In [ ]:
X=df_new[['square_feet','num_state', 'num_city']]
y=df_new['price']
trainX,testX,trainY,testY=train_test_split(X,y,test_size=0.2,random_state=234)

In [ ]:
model=linear_regression.fit(trainX,trainY)
pred=model.predict(testX)
print("r2=",r2_score(testY,pred))
print('mape=',mean_absolute_percentage_error(testY,pred))
print('rmse=',np.sqrt(mean_squared_error(testY,pred)))
plt.scatter(testY,pred)
plt.show()

In [ ]:
model=decision_tree.fit(trainX,trainY)
pred=model.predict(testX)
print("r2=",r2_score(testY,pred))
print('mape=',mean_absolute_percentage_error(testY,pred))
print('rmse=',np.sqrt(mean_squared_error(testY,pred)))
plt.scatter(testY,pred)
plt.show()

In [ ]:
model=xgboost.fit(trainX,trainY)
pred=model.predict(testX)
print("r2=",r2_score(testY,pred))
print('mape=',mean_absolute_percentage_error(testY,pred))
print('rmse=',np.sqrt(mean_squared_error(testY,pred)))
plt.scatter(testY,pred)
plt.show()

In [ ]:
model=random_forest.fit(trainX,trainY)
pred=model.predict(testX)
print("r2=",r2_score(testY,pred))
print('mape=',mean_absolute_percentage_error(testY,pred))
print('rmse=',np.sqrt(mean_squared_error(testY,pred)))
plt.scatter(testY,pred)
plt.show()